name: Run 189cloud

on:
  push:
    branches:
      - main
      - '189_cloud_drive/**'
  watch:
    types: started
  schedule:
    - cron: 35 18 * * *

jobs:
  cloud189-check-in:
    runs-on: ubuntu-latest
    environment: adrien

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r 189_cloud_drive/requirements.txt
        
    - name: Run Cloud189 script
      run: |
        # cloud189_user='${{ secrets.CLOUD189_USER }}'
        # cloud189_pwd='${{ secrets.CLOUD189_PWD }}'
        python3 189_cloud_drive/checkin.py --username '${{ secrets.CLOUD189_USER }}' --password '${{ secrets.CLOUD189_PWD }}'
        done
