name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
    paths:
      - 'baidutieba/*.py'
  watch:
    types: started
  schedule:
    - cron: 35 19 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python main.py
