name: 'Baidu Tieba Auto Sign'

on:
  push:
    branches:
      - main
    paths:
      - 'baidutieba/*.py'
  watch:
    types: started
  schedule:
    - cron: 35 19 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
        
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
        
      - name: 'Run baidutieba script'
        env:
           #baidutieba
          BDUSS: ${{ secrets.BDUSS }}
           # Telegram
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
        run: python baidutieba/main.py
