name: Run 189cloud
on:
  push:
    branches:
      - main
    paths:
      - 'cloud189/*.*'
  watch:
    types: started
  schedule:
    - cron: 25 19 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
    - uses: actions/checkout@v3
      with:
        path: cloud189  # 指定要将代码检出到的子文件夹 "cloud189"
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: init
      run: |
        cd cloud189  # 进入子文件夹 "cloud189"
        npm install  # 在子文件夹中安装依赖项
    - name: run
      id: run
      uses: nick-fields/retry@v2
      env:
        TY_USER_NAME: ${{secrets.TY_USER_NAME}}
        TY_PASSWORD: ${{secrets.TY_PASSWORD}}
        TY_USER_NAME1: ${{secrets.TY_USER_NAME1}}
        TY_PASSWORD1: ${{secrets.TY_PASSWORD1}}
        TY_USER_NAME2: ${{secrets.TY_USER_NAME2}}
        TY_PASSWORD2: ${{secrets.TY_PASSWORD2}}
        TY_USER_NAM3: ${{secrets.TY_USER_NAM3}}
        TY_PASSWORD3: ${{secrets.TY_PASSWORD3}}
        TY_USER_NAME4: ${{secrets.TY_USER_NAME4}}
        TY_PASSWORD4: ${{secrets.TY_PASSWORD4}}
        # Server
        SENDKEY: ${{secrets.SENDKEY}}
        # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: npm start
