name: Ikuuu Auto Sign

on:
  push:
    branches:
      - main
    paths:
      - 'ikuuu/*.py'
  watch:
    types: started
  schedule:
    - cron: 30 19 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requests and BeautifulSoup
      run: |
          pip install requests
          pip install lxml
          
    - name: Run ikuuu script
      env:
         #ikuuu
        IKUUU_ACCOUNTS: ${{ secrets.IKUUU_ACCOUNTS }}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: python ikuuu/ikuuuu_account.py
