name: moxing

on:
  push:
    branches:
      - main
    paths:
      - 'moxing/*.py'
  watch:
    types: started
  schedule:
    - cron: 20 19 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install --upgrade pip
        pip install --upgrade requests
        pip install ddddocr
        pip install Pillow==9.5.0
        pip install selenium

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chromedriver-linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version

    - name: Run moxing script
      env:
         #moxing
        MOXING_USERNAME: ${{secrets.MOXING_USERNAME}}
        MOXING_PSW: ${{secrets.MOXING_PSW}}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: |
        python moxing/moxing.py
           
