name: MoXing Auto Sign

on:
  push:
    branches:
      - main
    paths:
      - 'moxing/*.py'
  watch:
    types: started
  schedule:
    - cron: 20 19 * * *
    
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install --upgrade pip
        pip install --upgrade requests
        pip install ddddocr
        pip install Pillow==9.5.0
        pip install selenium

    - name: Install Chromedriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional

    - name: Run moxing script
      env:
         #moxing
        MOXING_USERNAME: ${{secrets.MOXING_USERNAME}}
        MOXING_PSW: ${{secrets.MOXING_PSW}}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: |
        python moxing/moxing.py
           
