name: moxing

on:
  push:
    branches:
      - main
    paths:
      - 'moxing/*.py'
  watch:
    types: started
  schedule:
    - cron: 20 19 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install --upgrade pip
        pip install --upgrade requests
        pip install ddddocr
        pip install Pillow==9.5.0
        pip install selenium

    - name: Prepare chromedriver
      uses: nanasess/setup-chromedriver@v2
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '117.0.5938.92'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional

    - name: Run moxing script
      env:
         #moxing
        MOXING_USERNAME: ${{secrets.MOXING_USERNAME}}
        MOXING_PSW: ${{secrets.MOXING_PSW}}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: |
        python moxing/moxing.py
           
