name: Run moxing

on:
  push:
    branches:
      - main
    paths:
      - 'moxing/*.py'
  watch:
    types: started
  schedule:
    - cron: 20 19 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install --upgrade pip
        pip install --upgrade requests
        pip install ddddocr
        pip install Pillow==9.5.0
        pip install selenium

    - name: Prepare chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Run moxing script
      env:
         #moxing
        MOXING_USERNAME: ${{secrets.MOXING_USERNAME}}
        MOXING_PSW: ${{secrets.MOXING_PSW}}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: |
        sudo cp -p ./chromedriver /usr/bin/
        chmod -R 777 /usr/bin/chromedriver
         python moxing/moxing.py
           
