name: MoXing Auto Sign

on:
  push:
    branches:
      - main
    paths:
      - 'moxing/*.py'
  watch:
    types: started
  schedule:
    - cron: 20 19 * * *
    
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: adrien
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install --upgrade pip
        pip install --upgrade requests
        pip install ddddocr
        pip install Pillow==9.5.0
        pip install selenium

    - name: Install Chrome and Chromedriver
      run: |
        # Install Chrome.
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Get Chrome version.
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
        # Use Chrome version to download corresponding Chromedriver.
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod 0755 /usr/local/bin/chromedriver

    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional

    - name: Run moxing script
      env:
         #moxing
        MOXING_USERNAME: ${{secrets.MOXING_USERNAME}}
        MOXING_PSW: ${{secrets.MOXING_PSW}}
         # Telegram
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
      run: |
        python moxing/moxing.py
           
